# Generated by Django 4.2.21 on 2025-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_inputs", "0003_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("question", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
