# Generated by Django 4.2.21 on 2025-05-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_inputs", "0004_questions"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInput",),
    ]
