# Generated by Django 4.2.21 on 2025-05-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_inputs", "0006_rating_question_alter_questions_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="qa", name="name",),
        migrations.AddField(
            model_name="qa",
            name="query",
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qa",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query",
                to="user_inputs.questions",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="user_inputs.questions",
            ),
        ),
    ]
